### ISSUE TITLE
ROS 2 Jazzy

### ISSUE THREAD

**Issue by lreiher** [nobleo/rviz_satellite#123]
Any plans to release this for ROS 2 Jazzy in the next few weeks? :)

**Comment by Timple** [comment]
Way ahead of ya: https://github.com/ros2-gbp/ros2-gbp-github-org/issues/525

Pending repository on ros2-gbp

**Comment by lreiher** [comment]
Awesome, thanks! I had only checked the rosdistro PRs . ;)

**Comment by Timple** [comment]
Pending: https://github.com/ros/rosdistro/pull/41430

The default branch is now ROS2 capable. You might need to adjust your scripts for this.
