### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by beetleskin** [nobleo/rviz_satellite#78]
.. or should we rather stick with the ROS buildfarm hooks?

However, we should incorporate basic CI checks, linting and unit-testing.

**Comment by schra** [comment]
Yeah this is something that we definitely should do. I also think integration into the ROS buildfarm is something we should do anyway.

It seems that there is no GitHub-integration of the ROS buildfarm? If you look at a ROS repo, for example https://github.com/ros-planning/moveit, they always use Travis.

I'm not familiar with both GitHub actions or Travis, but I'll have a look at this.

**Comment by schra** [comment]
Idea from #79:

> what about clang-format and camelCase vs. under_score? Can one set that in the config? Or is that only something clang-tidy can do? Should we add a clang-tidy config? Is there one for ROS? I only know the one from moveit (https://github.com/ros-planning/moveit/blob/master/.clang-tidy).

**Comment by Timple** [comment]
Enabled ros_industrial CI with catkin_lint
