### ISSUE TITLE
ROS build farm integration

### ISSUE THREAD

**Issue by Timple** [nobleo/rviz_satellite#80]
I've noticed a lot of refactoring being done. Glad to see this code is maintained!

Would you also be interested in creating a release for melodic so we don't need to build from source?

Thanks for considering!

**Comment by schra** [comment]
Not totally sure what you are referring to with a Melodic release.

But regarding not building from source: Integration into the ROS build farm is something that we might do in the future. What I can definitely do however, is to attach a .deb file to next releases.

**Comment by Timple** [comment]
Integration into the ROS build farm is exactly what I meant. It is like a 2 hour job the [first time](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease) you do it. After that pushing updates is easy.

No need to attach .deb files, that would be a-typical from all other ROS packages and (thus) we wouldn't use that.

Thanks for considering!

**Comment by Timple** [comment]
Today a [call for testing](https://discourse.ros.org/t/ros-noetic-call-for-testing/14203) was done on discourse for Noetic, so when this issue is picked up, please also release for Noetic :slightly_smiling_face:

**Comment by Timple** [comment]
Would you mind if I release your package to the buildfarm?

**Comment by Timple** [comment]
Pending: https://github.com/ros/rosdistro/pull/28039
