### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by Timple** [nobleo/rviz_satellite#99]
Placeholder issue.

If anyone is interested in picking this up, let me know!

Seems some initial work has been done here: https://github.com/blacksoul000/rviz_satellite/tree/dashing

Some more work here it seems: https://github.com/Kettenhoax/rviz_satellite

**Comment by vinnnyr** [comment]
There is a `ros2` branch here, but the README contains this text

> In the near future this plugin will not add support for ROS 2. For an unofficial ROS 2 fork see [blacksoul000/rviz_satellite](https://github.com/blacksoul000/rviz_satellite/tree/dashing).

I am  a little confused -- is this branch usable or not?

**Comment by Timple** [comment]
We have not made any effort yet in this direction.

Perhaps the fork will open a PR here. Or somebody else.
I am not sure if the `ros2` branch is usable at the moment.

**Comment by mr337** [comment]
Just curious what it would take to get ROS2 merged into this repo? A combination of https://github.com/Kettenhoax/rviz_satellite and a few tiny fixes https://github.com/Kettenhoax/rviz_satellite/pull/1 works great.

![shutter_004](https://user-images.githubusercontent.com/413937/217371380-5799c3f8-7225-4bab-aed9-c3ede512d78a.jpg)

**Comment by Timple** [comment]
Would you mind combining the efforts of those two in a single PR and target the ROS2 branch?

That should certainly get the ball rolling!

**Comment by Timple** [comment]
Thanks all. I took the liberty of releasing the binary to the buildfarm.

Feel free to test using the testing ppa.
